global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: bobo-backend
    metrics_path: /metrics
    authorization:
      credentials: ${METRICS_ACCESS_TOKEN}
    static_configs:
      - targets: ["backend_blue:8000", "backend_green:8000"]
        labels:
          app: bobo-backend

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  - job_name: promtail
    static_configs:
      - targets: ["promtail:9080"]
